CREATE TABLE IF NOT EXISTS FILM_RATING (
	FILM_RATING_ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50) NOT NULL,
	DESCRIPTION CHARACTER VARYING(255),
	CONSTRAINT FILM_RATING_PK PRIMARY KEY (FILM_RATING_ID)
);

CREATE TABLE IF NOT EXISTS LIKES (
	FILM_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
    CONSTRAINT LIKES_PK PRIMARY KEY (FILM_ID, USER_ID)
);


CREATE TABLE IF NOT EXISTS USERS (
	USER_ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING(50) NOT NULL,
	LOGIN CHARACTER VARYING(50) NOT NULL,
	NAME CHARACTER VARYING(50),
	BIRTHDAY DATE NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS FILMS (
	FILM_ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50) NOT NULL,
	DESCRIPTION CHARACTER VARYING(255),
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	FILM_RATING BIGINT,
	CONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP (
	USER_FIRST_ID BIGINT NOT NULL,
	USER_SECOND_ID BIGINT NOT NULL,
	CONSTRAINT FRIENDSHIP_PK PRIMARY KEY (USER_FIRST_ID, USER_SECOND_ID)
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
	FILM_ID BIGINT NOT NULL,
	GENRE BIGINT NOT NULL,
	CONSTRAINT FILM_GENRE_PK PRIMARY KEY (FILM_ID, GENRE)
);

CREATE TABLE IF NOT EXISTS genres (
	GENRE_ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT GENRE_PK PRIMARY KEY (GENRE_ID)
);

ALTER TABLE FILMS ADD CONSTRAINT IF NOT EXISTS FILMS_FILM_RATING_FK FOREIGN KEY (FILM_RATING) REFERENCES FILM_RATING(FILM_RATING_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FILM_GENRE ADD CONSTRAINT IF NOT EXISTS FILM_GENRE_FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES FILMS(FILM_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FILM_GENRE ADD CONSTRAINT IF NOT EXISTS FILM_GENRE_GENRE_FK FOREIGN KEY (GENRE) REFERENCES genres(GENRE_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE LIKES ADD CONSTRAINT IF NOT EXISTS LIKES_FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES FILMS(FILM_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE LIKES ADD CONSTRAINT IF NOT EXISTS LIKES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FRIENDSHIP ADD CONSTRAINT IF NOT EXISTS FRIENDSHIP_USERS_FK FOREIGN KEY (USER_FIRST_ID) REFERENCES USERS(USER_ID);
ALTER TABLE FRIENDSHIP ADD CONSTRAINT IF NOT EXISTS FRIENDSHIP_USERS_FK_1 FOREIGN KEY (USER_SECOND_ID) REFERENCES USERS(USER_ID);








