INSERT INTO USERS
(EMAIL, LOGIN, NAME, BIRTHDAY)
VALUES('hjgljg@jhbb.ru', 'xvxv', 'zxvzvz', '2024-12-01');

INSERT INTO FILMS
(NAME, DESCRIPTION, RELEASE_DATE, DURATION, FILM_RATING)
VALUES('film1', 'film1', '2024-04-01', 1, 1);